/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        // Andaman Brand Colors from tailwind.config.js
        teal: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          200: '#99f6e4',
          300: '#5eead4',
          400: '#2dd4bf',
          500: '#0d9e8a',
          600: '#0d6e8e',
          700: '#0e5a74',
          800: '#134e62',
          900: '#144356',
          950: '#092a38',
        },
        coral: {
          50: '#fff4f2',
          100: '#ffe5df',
          200: '#ffcfc5',
          300: '#ffad9e',
          400: '#ff8a76',
          500: '#ff6b4a',
          600: '#f04830',
          700: '#cb3420',
          800: '#a82b1c',
          900: '#8c281d',
        },
        sandy: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#f5c842',
          500: '#eaaa15',
          600: '#c98a0e',
          700: '#a36a10',
          800: '#855415',
          900: '#6f4514',
        },
        warm: {
          50: '#fafaf7',
          100: '#f5f5f0',
          200: '#ecece4',
          300: '#d9d9cd',
          400: '#b8b8a9',
          950: '#e8e8e0',
        },
        midnight: {
          500: '#162236',
          600: '#0e1928',
          700: '#0b1a2e',
          800: '#070f1a',
          900: '#040b13',
        },
        ocean: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
      },
      fontFamily: {
        sans: ['Instrument Sans', 'Inter', 'system-ui', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'Outfit', 'sans-serif'],
        display: ['DM Serif Display', 'Playfair Display', 'Georgia', 'serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '2xl': '16px',
        '3xl': '24px',
        '4xl': '32px',
      },
      boxShadow: {
        card: '0 2px 12px rgba(0, 0, 0, 0.06), 0 1px 3px rgba(0, 0, 0, 0.04)',
        'card-hover': '0 12px 40px rgba(13, 110, 142, 0.15)',
        soft: 'var(--shadow-soft)',
        floating: 'var(--shadow-floating)',
        glass: '0 8px 32px rgba(0, 0, 0, 0.08), inset 0 1px 0 rgba(255,255,255,0.6)',
        nav: 'var(--shadow-nav)',
        'teal-glow': '0 8px 32px rgba(13, 110, 142, 0.25)',
        'coral-glow': '0 8px 32px rgba(255, 107, 74, 0.25)',
        'ocean-glow': 'var(--shadow-ocean-glow)',
        'sandy-glow': '0 8px 32px rgba(245, 200, 66, 0.25)',
      },
      backgroundImage: {
        'teal-gradient': 'linear-gradient(135deg, #0d9e8a 0%, #0d6e8e 100%)',
        'coral-gradient': 'linear-gradient(135deg, #ff8a76 0%, #ff6b4a 100%)',
        'sandy-gradient': 'linear-gradient(135deg, #fcd34d 0%, #f5c842 100%)',
        'midnight-gradient': 'linear-gradient(180deg, #0b1a2e 0%, #162236 100%)',
        'island-hero': 'linear-gradient(135deg, #0d6e8e 0%, #0d9e8a 50%, #14b8a6 100%)',
        'cat-fish': 'linear-gradient(135deg, #0d6e8e, #0d9e8a)',
        'cat-produce': 'linear-gradient(135deg, #16a34a, #4ade80)',
        'cat-crafts': 'linear-gradient(135deg, #9333ea, #c084fc)',
        'cat-experience': 'linear-gradient(135deg, #0284c7, #38bdf8)',
        'cat-rentals': 'linear-gradient(135deg, #ca8a04, #fde68a)',
        'cat-services': 'linear-gradient(135deg, #dc2626, #f87171)',
        'cat-general': 'linear-gradient(135deg, #475569, #94a3b8)',
        'cat-tourism': 'linear-gradient(135deg, #ff6b4a, #fcd34d)',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        'slide-in-right': 'slideInRight 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'pulse-heart': 'pulseHeart 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'float': 'float 3s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite linear',
        'wave': 'wave 2.5s ease-in-out infinite',
        'carousel': 'carousel 0.5s cubic-bezier(0.16, 1, 0.3, 1)',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      keyframes: {
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(20px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        pulseHeart: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.4)' },
          '100%': { transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        wave: {
          '0%, 100%': { transform: 'scaleY(1)' },
          '50%': { transform: 'scaleY(0.7)' },
        },
        carousel: {
          from: { opacity: '0', transform: 'translateX(30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('daisyui'),
  ],
  daisyui: {
    themes: ["light"],
  },
};
