export const KNOWN_LOCATIONS = [
  "Port Blair",
  "North Bay",
  "Corbyn's Cove",
  "Rajiv Gandhi Water Sports Complex",
  "Chidiyatapu",
  "Havelock Elephant Beach",
  "Neil Bharatpur",
  "Jolly Buoy",
];

export const KNOWN_TYPES = [
  "Adventure",
  "Aerial",
  "Beginner",
  "Cruise",
  "Diving",
  "Eco",
  "Family",
  "Fishing",
  "Fitness",
  "Fun",
  "Group",
  "Leisure",
  "Motorized",
  "Nature",
  "Paddle",
  "Premium",
  "Reef",
  "Sailing",
  "Sightseeing",
  "Skill",
  "Thrill",
  "Underwater",
];

export const KNOWN_ACTIVITY_NAMES = [
  "Scuba Diving",
  "Sea Walking",
  "Snorkeling",
  "Parasailing",
  "Jet Skiing",
  "Speed Boat",
  "Banana Boat",
  "Glass Bottom Boat",
  "Semi-Submarine",
  "Kayaking",
  "Windsurfing",
  "Sea Karting",
  "Sport Fishing",
  "Seaplane",
  "Harbour Cruise",
  "SUP",
  "Water Skiing",
  "Mangrove Kayaking",
];
